#spring.application.name=message-generator

#POSTGRES
spring.datasource.url=jdbc:postgresql://localhost:5432/sbank
spring.datasource.username=postgres
spring.datasource.password=daniel
spring.datasource.driver-name=org.postgresql.Driver

#JPA
spring.jpa.properties.temp.use_jdbc_metadata_defaults = false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#Hibernate dll auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update