SELECT * FROM ALUNOS;
INSERT INTO ALUNOS VALUES('FRANCISCA',3,'JAVA');
INSERT INTO ALUNOS VALUES('ELISA',3,'JAVA');
INSERT INTO ALUNOS VALUES('BERNARDO',1,'JAVA');
INSERT INTO ALUNOS VALUES('DANIEL',37,'JAVA');
SELECT * FROM ALUNOS;

