[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; ---------------------------------------------------------
; Bibliotecas externas (PlatformIO instala automaticamente)
; ---------------------------------------------------------
lib_deps =
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library

; ---------------------------------------------------------
; Flags de compilação (avisos úteis e código mais seguro)
; ---------------------------------------------------------
build_flags =
    -Wall                 ; avisos essenciais
    -Wextra               ; avisos adicionais
    -Werror=return-type   ; obriga funções a devolver valor
    -Wno-unused-variable  ; ignora variáveis não usadas
    -Wno-unused-parameter ; ignora parâmetros não usados
    -I src                ; inclui a pasta src/ nos headers

; ---------------------------------------------------------
; Serial monitor e upload
; ---------------------------------------------------------
upload_speed = 115200     ; velocidade segura para ESP32
monitor_speed = 115200    ; velocidade do Serial Monitor

; ---------------------------------------------------------
; Porta COM automática (ideal quando muda sempre)
; ---------------------------------------------------------
; upload_port = auto        ; PlatformIO escolhe a porta correta
; monitor_port = auto       ; idem para o monitor serial
upload_port = COM11
monitor_port = COM11